kind: pipeline
name: Build and Publish CMS
type: docker

steps:
  - name: Publish CMS
    image: plugins/docker
    environment:
      SESSION_SECRET:
        from_secret: SESSION_SECRET
    when:
      branch:
        - main
      event:
        exclude:
          - pull_request
    pull: if-not-exists
    settings:
      purge: true
      cache_from: ghcr.io/sebasptsch/nextcms
      target: production
      build_args_from_env:
        - SESSION_SECRET
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      repo: ghcr.io/sebasptsch/nextcms
      auto_tag: false
      pull: true
      tags:
        - latest
        - ${DRONE_COMMIT}
      registry: ghcr.io
      dockerfile: keystone.Dockerfile
trigger:
  event:
    exclude:
      - promote
---
kind: pipeline
name: Build and Publish Frontend
type: docker

steps:
  - name: Build and Publish
    image: plugins/docker
    environment:
      GRAPHQL_ENDPOINT:
        from_secret: GRAPHQL_ENDPOINT
    when:
      branch:
        - main
      event:
        exclude:
          - pull_request
    pull: if-not-exists
    settings:
      purge: true
      cache_from: ghcr.io/sebasptsch/nextblog
      target: production
      pull: true
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      repo: ghcr.io/sebasptsch/nextblog
      registry: ghcr.io
      auto_tag: false
      tags:
        - latest
        - ${DRONE_COMMIT}
      dockerfile: frontend.Dockerfile
      build_args_from_env:
        - GRAPHQL_ENDPOINT
trigger:
  event:
    exclude:
      - promote
# ---
# kind: pipeline
# type: docker
# name: Deploy
# steps:
#   - name: Deploy Using Ansible
#     image: plugins/ansible
#     pull: if-not-exists
#     environment:
#       GRAPHQL_ENDPOINT: https://cms.sebasptsch.dev/api/graphql
#       SESSION_SECRET:
#         from_secret: SESSION_SECRET
#     settings:
#       playbook: .ansible/playbook.yml
#       ssh_extra_args:
#         - "-o StrictHostKeyChecking=no"
#       galaxy: .ansible/requirements.yml
#       inventory: .ansible/inventory
#       user: sebas
#       private_key:
#         from_secret: ansible_private_key
# trigger:
#   event:
#     - promote
#   target:
#     - production
