---
kind: pipeline
type: exec
name: default

steps:
  - name: Log In
    environment:
      GITHUB_USERNAME:
        from_secret: github_username
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - docker login -u $GITHUB_USERNAME -p $GITHUB_TOKEN
  - name: Hello
    commands:
      - echo hello world
