---
kind: pipeline
type: docker
name: default
steps:
  - name: Restore Cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./node_modules
        - ./frontend/.next/cache
        - ./keystone/admin/.next/cache

  - name: Install Dependencies
    pull: if-not-exists
    image: node:lts-buster
    depends_on:
      - "Restore Cache"
    commands:
      - "yarn install --frozen-lockfile --production"

  - name: "Build Keystone"
    pull: if-not-exists
    image: node:lts-buster
    environment:
      SESSION_SECRET:
        from_secret: SESSION_SECRET
    depends_on:
      - "Install Dependencies"
    commands:
      - "yarn build:keystone"

  - name: "Build Frontend"
    pull: if-not-exists
    image: node:lts-buster
    environment:
      GRAPHQL_ENDPOINT:
        from_secret: GRAPHQL_ENDPOINT
    depends_on:
      - "Install Dependencies"
    commands:
      - "yarn build:frontend"

  - name: Rebuild Cache
    pull: if-not-exists
    image: drillster/drone-volume-cache
    depends_on:
      - "Build Keystone"
      - "Build Frontend"
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
        - ./frontend/.next/cache
        - ./keystone/admin/.next/cache

  - name: Publish CMS
    pull: if-not-exists
    image: plugins/docker
    depends_on:
      - "Build Keystone"
    environment:
      SESSION_SECRET:
        from_secret: SESSION_SECRET
    when:
      branch:
        - main
      event:
        exclude:
          - pull_request
    settings:
      build_args_from_env:
        - SESSION_SECRET
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      repo: ghcr.io/sebasptsch/nextcms
      registry: ghcr.io
      dockerfile: keystone.Dockerfile
  - name: Publish Frontend
    pull: if-not-exists
    image: plugins/docker
    depends_on:
      - "Build Frontend"
    environment:
      GRAPHQL_ENDPOINT:
        from_secret: GRAPHQL_ENDPOINT
    when:
      branch:
        - main
      event:
        exclude:
          - pull_request
    settings:
      build_args_from_env:
        - GRAPHQL_ENDPOINT
      username:
        from_secret: github_username
      password:
        from_secret: github_token
      repo: ghcr.io/sebasptsch/nextblog
      registry: ghcr.io
      dockerfile: frontend.Dockerfile

volumes:
  - name: cache
    host:
      path: /tmp/cache
