---
version: "3"
services:
  frontend:
    container_name: frontend
    depends_on:
      - cms
    build:
      context: ./
      dockerfile: frontend.Dockerfile
      args:
        GRAPHQL_ENDPOINT: https://cms.sebasptsch.dev/api/graphql
    networks:
      - blog
    ports:
      - "3001:3000"
  cms:
    container_name: cms
    build:
      context: ./
      dockerfile: keystone.Dockerfile
    ports:
      - "3002:3002"
    networks:
      - blog
    volumes:
      - ./keystone/config:/app/keystone/config
networks:
  blog:
