---
version: "3"
services:
  frontend:
    container_name: frontend
    depends_on:
      - cms
    build:
      context: ./
      dockerfile: frontend.Dockerfile
      args:
        GRAPHQL_ENDPOINT: http://cms:3002/api/graphql
    networks:
      - blog
    ports:
      - "3001:3000"
    env_file: frontend/.env.development.local
  cms:
    container_name: cms
    build:
      context: ./
      dockerfile: keystone.Dockerfile
      args:
        NODE_ENV: development
    ports:
      - "3002:3002"
    networks:
      - blog
    volumes:
      - db:/app/keystone/config
    env_file: keystone/.env.development.local
networks:
  blog:

volumes:
  db:
